name: Dart/Flutter Package Analyzer

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, staging, dev ]
  pull_request:
    branches: [ master, staging, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # This action uses the pana (Package ANAlysis) package to compute the score that 
    # your Dart or Flutter package will have on the Pub site, and annotates your code, 
    # with suggestions for improvements.
    - name: Dart/Flutter Package Analyzer
      uses: axel-op/dart-package-analyzer@v2.0.0
      with:
        # Required:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
      
